services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB?variable not set}
      POSTGRES_USER: ${POSTGRES_USER?variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?variable not set}
      POSTGRES_PORT: ${POSTGRES_PORT?variable not set}
    ports:
      - ":${POSTGRES_HOST_PORT}:5432"
    volumes:
      - app-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  prestart:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    command: bash scripts/prestart.sh
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
    depends_on:
      prestart:
        condition: service_completed_successfully
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      BACKEND_URL: http://backend:8000

    depends_on:
      - backend

    command: bun run dev -- --hostname 0.0.0.0

volumes:
  app-db-data:
  backend_venv:
  frontend_node_modules:
