services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB?variable not set}
      POSTGRES_USER: ${POSTGRES_USER?variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?variable not set}
      POSTGRES_PORT: ${POSTGRES_PORT?variable not set}
    ports:
      - ":${POSTGRES_PORT}:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  app-db-data:
