"""rename color_key to color_tag

Revision ID: a869609614c3
Revises: a0ed34440283
Create Date: 2026-08-03 15:03:39.692748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a869609614c3'
down_revision: Union[str, Sequence[str], None] = 'a0ed34440283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('color_tag', sa.String(length=30), server_default='blue', nullable=False))
    op.drop_column('collections', 'color_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('color_key', sa.VARCHAR(length=30), server_default=sa.text("'blue'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('collections', 'color_tag')
    # ### end Alembic commands ###
